server:
  port: 3000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seneca_forum
    username: root
    password: abc123456
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        format_sql: true
        #to fix the bug 'Failed to lazily initialize a collection of role could not initialize proxy â€“ no Session'
        enable_lazy_load_no_trans: true
secretKey: fPJZz!YkEmUhdmvvhw7y*6K*0$7vco!pfiOtq6N&cgnLNT$I4u
#  servlet:
#    multipart:
#      enabled: true
#      max-file-size: 128MB
#      max-request-size: 128MB
#  resources:
#    static-locations: classpath:/videos/


